### ISSUE TITLE
Create webhooks

### ISSUE THREAD

**Issue by StephenStrickland** [ksubcm/website#21]
We can setup a webhook for this repo. So that it will auto pull changes to dev.

**Comment by theNerd247** [comment]
I saw this when I was initially working on the deployment script. If I remember correctly, the reason why I chose not to go this route was because we will have to deal with HTTP POST protocol and stuffs and for our needs all we needed was a simple script. If we will need more features than just deploy-on-push than I'll look into it later on. If we get a cloud server this might be an option.

**Comment by StephenStrickland** [comment]
you can have it call ksubcm.com/file_that_pulls.php and let this file pull.

**Comment by theNerd247** [comment]
I could but that's pretty much what we already have.

**Comment by theNerd247** [comment]
This discussion is a bit old...I'm closing it..
